export const members = [
  {
    id: '1',
    name: 'Artem Karpenko',
    role: 'Team lead',
    img: 'https://avatars.githubusercontent.com/u/101360953?v=4',
    gitHubLink: 'https://github.com/Ozozai12',
    LinkdInLink:'',
    discription:
      'Styding at GoIT as a full-stack developer.',
  },
  {
    id: '2',
    name: 'Olga Mykhailova',
    role: 'Scrum-master',
    img: 'https://avatars.githubusercontent.com/u/100313107?v=4',
    gitHubLink: 'https://github.com/OlgaMykhailova',
    LinkdInLink: '',
    discription:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic nulla distinctio molestias unde omnis cum error, aliquid tempora veritatis vitae.',
  },
  {
    id: '3',
    name: 'Olena Hras',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/100197147?v=4',
    gitHubLink: 'https://github.com/OlenaHras',
    LinkdInLink: '',
    discription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic nulla distinctio molestias unde omnis cum error, aliquid tempora veritatis vitae.',
  },
  {
    id: '4',
    name: 'Anastasiya Olhovik',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/93829935?v=4',
    gitHubLink: 'https://github.com/AnastasiyaOlhovik',
    LinkdInLink: '',
    discription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic nulla distinctio molestias unde omnis cum error, aliquid tempora veritatis vitae.',
  },
  {
    id: '5',
    name: 'Pavel Kreitsberg',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/99120090?v=4',
    gitHubLink: 'https://github.com/PavelKreitsberg',
    LinkdInLink: '',
    discription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic nulla distinctio molestias unde omnis cum error, aliquid tempora veritatis vitae.',
  },
  {
    id: '6',
    name: 'Xdecent',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/100188867?v=4',
    gitHubLink: 'https://github.com/Xdecent0',
    LinkdInLink: '',
    discription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic nulla distinctio molestias unde omnis cum error, aliquid tempora veritatis vitae.',
  },
  {
    id: '7',
    name: 'Oleksii Shevchenko',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/94850347?v=4',
    gitHubLink: 'https://github.com/oleksii-she',
    LinkdInLink: '',
    discription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic nulla distinctio molestias unde omnis cum error, aliquid tempora veritatis vitae.',
  },
  {
    id: '8',
    name: 'wi2410',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/101503219?v=4',
    gitHubLink: 'https://github.com/wi2410',
    LinkdInLink: '',
    discription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic nulla distinctio molestias unde omnis cum error, aliquid tempora veritatis vitae.',
  },
  {
    id: '9',
    name: 'Valeriia Masiuk',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/99878558?v=4',
    gitHubLink: 'https://github.com/ValeriiaMasiuk',
    LinkdInLink: '',
    discription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic nulla distinctio molestias unde omnis cum error, aliquid tempora veritatis vitae.',
  },
  {
    id: '10',
    name: 'Valeriia Masiuk',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/99878558?v=4',
    gitHubLink: 'https://github.com/ValeriiaMasiuk',
    LinkdInLink: '',
    discription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic nulla distinctio molestias unde omnis cum error, aliquid tempora veritatis vitae.',
  },
  {
    id: '11',
    name: 'Klyimus Vlad',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/99616484?v=4',
    gitHubLink: 'https://github.com/klimchanskii',
    LinkdInLink: '',
    discription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic nulla distinctio molestias unde omnis cum error, aliquid tempora veritatis vitae.',
  },
  {
    id: '12',
    name: 'Oleksii Reshetnyk',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/55344626?v=4',
    gitHubLink: 'https://github.com/oreshnyk',
    LinkdInLink: '',
    discription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic nulla distinctio molestias unde omnis cum error, aliquid tempora veritatis vitae.',
  },
];